### ISSUE TITLE
Production style class name generation seems have a possibility to generate broken class names

### ISSUE THREAD

**Issue by jkorpelin** [roosta/herb#7] opened 2020-07-06 12:50 UTC
Production build generated a class name `-3n_226459910`, the style definition exists with that exact name but doesn't get applied to the element. I'm assuming it has something to do with the fact that css classes can't begin with an unescaped number and the line at the beginning doesn't help.

**Comment by roosta** [comment] 2020-07-06 15:00
That's unfortunate, I haven't experienced that myself. Is is due to closure compiler renaming a JavaScript function to -3n? Is that a legal JavaScript function name? Is that the full class name? A possible solution is to strip away illegal characters, should work without a collision since its got a hash appended to the end.

Do you have steps to reproduce? I'm guessing it could be difficult, but I'd love to have something to test against.

**Comment by roosta** [comment] 2020-07-06 16:20
I've created a possible fix, you mind trying out: https://clojars.org/herb/versions/0.10.1-SNAPSHOT

**Comment by roosta** [comment] 2020-07-06 16:20
I've created a possible fix, you mind trying out: https://clojars.org/herb/versions/0.10.1-SNAPSHOT

**Comment by roosta** [comment] 2020-07-06 16:31
Hmm, I think I need some more info as to how this happened, `-3n` isn't a valid js function name, so I don't quite understand how this happened. The fix might or might not work but I might have barked up the wrong tree so to speak.

**Comment by roosta** [comment] 2020-07-06 16:35
Could you set `goog.debug` to `true` and tell me what the `data-herb` attribute says?

**Comment by jkorpelin** [comment] 2020-07-07 06:13
The generated style tag has `data-herb="/-3n"`. And yea the only steps to reproduce I figured out is to build multiple times and at one point old styling fails, -3n is not a legal js function.

**Comment by jkorpelin** [comment] 2020-07-07 09:06
Running the build again with the new fix version seems to have helped. Not sure if running the build again with a new version just happened to generate another name for the class though.

**Comment by roosta** [comment] 2020-07-07 11:43
What I think is happening is that herb strips away any illegal characters when it creates a selector, but since both numbers and hyphens are technically legal, just not at the beginning of the classname it leaves that alone. The fix I pushed makes sure that there's no hyphen followed by a number, or just a number at the beginning of the classname https://github.com/roosta/herb/commit/62ded861a3ba9710a7010a7f88d3aa4c514a2dba.

What bothers me is that this situation shouldn't happen, since javascript symbol names should result in a valid CSS classname when its initially sanitized. I'll debug some more and see if I can figure out the cause, but the fix should work. I'll let you know what I come up.

**Comment by roosta** [comment] 2020-07-10 13:47
Is it the same style function that cause this issue every time? If so could you paste the function that's causing the issue? I'm having a hard time reproducing this issue, but I'd like to get to the root of this. Any details you could provide would be helpful.

**Comment by jkorpelin** [comment] 2020-08-03 06:30
Sorry I left for a vacation and couldn't get back to you.

I already applied your fix to all the builds so I haven't had the issue anymore. I remember it happening to at least 3 different style functions, which were located in the same section of code if that helps at all, I'll get back to you if the issue pops up again and I can give more information.

**Comment by roosta** [comment] 2020-08-03 09:01
Good to know the fix solved the issue so far, I'll draft a new version with it then. I'm still not sure why that would happen but I suspect it's the reason I mention above, although I can't be entirely sure. I've never encountered the issue myself, or at the very least not noticed it. Keep me posted if you find out anything else :)

**Comment by roosta** [comment] 2021-12-11 12:57
Closing this, the patch is now in `0.10.1`, was never able to reproduce but the fix seems stable, and unobtrusive enough.

**Closed as completed by roosta** 2021-12-11 12:57 UTC
Labels: unable to reproduce
